# only use these two lines with gae devserver
application: musicoin-web
version: 2
runtime: python27
api_version: 1
threadsafe: yes


handlers:

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /
  script: main.app

- url: /join
  script: main.app

- url: /join/.*
  script: main.app

- url: /\.well-known/acme-challenge/.*
  script: letsencrypt.app


- url: /(.+)
  static_files: public/\1
  upload: public/(.*)
  application_readable: true


skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
